# Member Night of Worship Junction Table
DROP TABLE IF EXISTS MEMBER_NIGHT_JUNCTION;
CREATE TABLE MEMBER_NIGHT_JUNCTION (
  MemberID INTEGER NOT NULL,
  NightID INTEGER NOT NULL,

  FOREIGN KEY(MemberID) REFERENCES MEMBERS(MemberID),

  FOREIGN KEY(NightID) REFERENCES NIGHTS_OF_WORSHIP(NightID),

  CONSTRAINT Member_Night_PK
     PRIMARY KEY(MemberID, NightID)
);

# Member Life Group Junction Table
DROP TABLE IF EXISTS MEMBER_LIFE_GROUP_JUNCTION;
CREATE TABLE MEMBER_LIFE_GROUP_JUNCTION (
  MemberID INTEGER NOT NULL,
  LifeGroupID INTEGER NOT NULL,

  FOREIGN KEY(MemberID) REFERENCES MEMBERS(MemberID),

  FOREIGN KEY(LifeGroupID) REFERENCES LIFE_GROUPS(LifeGroupID),

  CONSTRAINT Member_LifeGroup_PK
    PRIMARY KEY(MemberID, LifeGroupID)

);
